
### register as a user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "johnson",
  "email": "johnson@example.com",
  "password": "password123"
}
####
POST http://localhost:3000/auth/login
Content-Type: application/json

{
"email": "john2@gmail.com",
"password": "password123"
}
####
GET http://localhost:3000/protected-route
Authorization: Bearer
