
### register as a user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Peter",
  "email": "peterv@example.com",
  "password": "password123"
}
####
POST http://localhost:3000/auth/login
Content-Type: application/json

{
"email": "john@example.com",
"password": "password123"
}
####
GET http://localhost:3000/protected-route
Authorization: Bearer
