### Add Product to Cart
POST http://localhost:3000/cart/add/cmcam7tmw0002g9vkbtnxvmg3
Content-Type: application/json

{
  "productId": "cmceazhwn0000g9r465tng2o7",
  "quantity": 2
}

### Get User Cart
GET http://localhost:3000/cart/cmcam7tmw0002g9vkbtnxvmg3
