### create product
POST http://localhost:3000/products
Content-Type: application/json

{
 "name": "Mouse",
 "description": "wireless mouse",
  "price": "233354.00",
  "stock": 12,
  "imageUrl": "https://unsplash.com/photos/a-woman-runs-through-a-shadow-shaped-doorway-if0cWm_Y3jY"
}