### create product
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "keyboard",
  "description": "wireless",
  "price": "233355.00",
  "stock": 12,
  "imageUrl": "https://images.unsplash.com/photo-1587620970721-b1a85e0a0e26"
}


