### create user 

POST http://localhost:3000/users
Content-Type: application/json


{
  "name" : "Peter",
  "email": "njugunapeter@gmail.com",
  "password": "12345678",
  "role": "ADMIN"
}
#### GET ALL USERS

GET http://localhost:3000/users
Content-Type: application/json

#### GET ONE USER BY ID

GET http://localhost:3000/users/cmcd7ish90000g9jq7dzzikmp
Content-Type: application/json


### get user by email
GET http://localhost:3000/users/email/peter@gmail.com
Content-Type: application/json


### update user by id

PATCH  http://localhost:3000/users/cmcd7ish90000g9jq7dzzikmp
Content-Type: application/json

{
  "name" :"john",
  "email" :"tred@gmail.com"

}

### delete by id
DELETE http://localhost:3000/users/cmcd7ish90000g9jq7dzzikmp
Content-Type: application/json